services:
  redis:
    image: redis:8.6.2-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - MONITOR_INTERVAL=60000
      - URLS_TO_MONITOR=https://google.com,https://github.com,https://openai.com,https://microsoft.com,https://apple.com,https://amazon.com,https://netflix.com,https://spotify.com,https://x.com,https://linkedin.com
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api/status
    depends_on:
      - server
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
